# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 12:03
from __future__ import unicode_literals

from django.db import migrations

from coordinators.auth_migration_utils import get_coordinators_group, get_permissions


# TODO: should add rights first with a migration :)
def remove_location_and_shift_add_delete_rights(apps, schema_editor):
    coordinators_group = get_coordinators_group(apps)
    permissions = get_permissions(apps,
            ('locations', 'location', ('add', 'delete')),
            ('campaigns', 'campaignlocationshift', ('add', 'delete')))
    coordinators_group.permissions.remove(*permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        ('coordinators', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_location_and_shift_add_delete_rights),
    ]
