# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 22:35
from __future__ import unicode_literals

from django.db import migrations

from coordinators.auth_migration_utils import get_coordinators_group, get_permissions


def add_campaignlocationshiftparticipation_rights(apps, schema_editor):
    coordinators_group = get_coordinators_group(apps)
    permissions = get_permissions(apps,
            ('campaigns', 'campaignlocationshiftparticipation',
                ('add', 'change', 'delete')))
    coordinators_group.permissions.add(*permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        ('coordinators', '0002_auto_20161127_1403'),
    ]

    operations = [
        migrations.RunPython(add_campaignlocationshiftparticipation_rights),
    ]
