# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 21:55
from __future__ import unicode_literals

from django.db import migrations


from coordinators.auth_migration_utils import get_administrators_group, get_permissions


def add_campaignlocationshiftparticipation_rights(apps, schema_editor):
    administrators_group = get_administrators_group(apps)
    permissions = get_permissions(apps,
            ('campaigns', 'campaignlocationshiftparticipation',
                ('add', 'change', 'delete')))
    administrators_group.permissions.add(*permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        ('campaigns', '0014_campaignlocationshiftparticipation'),
        ('coordinators', '0003_auto_20161205_0035'),
    ]

    operations = [
        migrations.RunPython(add_campaignlocationshiftparticipation_rights),
    ]
