# Generated by Django 2.0 on 2017-12-27 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinators', '0004_auto_20161205_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.District', verbose_name='District'),
        ),
    ]
