# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='name',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='age',
            field=models.PositiveIntegerField(default=1, verbose_name=b'Vanus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name=b'E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name=b'Eesnimi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name=b'Perenimi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(default='', max_length=100, verbose_name=b'Telefon'),
            preserve_default=False,
        ),
    ]
