# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-28 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_auto_20160820_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': 'Volunteer', 'verbose_name_plural': 'Volunteers'},
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Phone'),
        ),
    ]
