# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-28 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_auto_20160828_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Group/organization name'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='is_group',
            field=models.BooleanField(default=False, verbose_name='Is group'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='members_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Members count'),
        ),
    ]
