# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-28 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_auto_20161028_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='members_count',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='participant_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Participant count'),
        ),
    ]
