# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-28 17:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0005_auto_20161028_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='participant_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Participant count'),
        ),
    ]
