# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-28 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0006_auto_20161028_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='is_group',
            field=models.BooleanField(default=False, verbose_name='Is group representative'),
        ),
    ]
