# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0007_auto_20161028_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterUniqueTogether(
            name='volunteer',
            unique_together=set([('email', 'group_name')]),
        ),
    ]
