# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0010_shiftleader'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='notes',
            field=models.CharField(blank=True, max_length=200, verbose_name='Notes'),
        ),
    ]
