# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0013_shiftleader_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftleader',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.District', verbose_name='District'),
        ),
    ]
