# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0014_auto_20161122_0031'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='volunteer',
            unique_together=set([('email', 'group_name', 'first_name', 'last_name')]),
        ),
        migrations.AlterIndexTogether(
            name='volunteer',
            index_together=set([('email', 'group_name', 'first_name', 'last_name')]),
        ),
    ]
