# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0015_auto_20161124_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
