# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0016_auto_20161124_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftleader',
            name='district',
        ),
        migrations.DeleteModel(
            name='ShiftLeader',
        ),
    ]
