# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0017_auto_20161127_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='public_notes',
            field=models.TextField(blank=True, verbose_name='Public notes'),
        ),
    ]
