# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 21:33
from __future__ import unicode_literals

from django.db import migrations

def add_district_to_existing_volunteers(apps, schema_editor):
    Participation = apps.get_model('campaigns', 'CampaignLocationShiftParticipation')
    for participation in Participation.objects.all():
        district = participation.shift.location.district
        participation.volunteer.districts.add(district)


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0019_volunteer_districts'),
        ('campaigns', '0020_auto_20161206_0114'),
    ]

    operations = [
        migrations.RunPython(add_district_to_existing_volunteers),
    ]
