# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-25 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0020_auto_20161223_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='registration_ip_address',
            field=models.GenericIPAddressField(db_index=True, default='127.0.0.1', verbose_name='Registration IP address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='registration_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Registration time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='registration_user_agent',
            field=models.CharField(default='None', max_length=255, verbose_name='Registration user agent'),
            preserve_default=False,
        ),
    ]
