# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-25 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0021_auto_20171125_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='registration_ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='Registration IP address'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='registration_user_agent',
            field=models.CharField(blank=True, max_length=255, verbose_name='Registration user agent'),
        ),
    ]
