# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='contacts',
        ),
        migrations.DeleteModel(
            name='LocationContact',
        ),
    ]
