# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20160820_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('district', 'name')]),
        ),
    ]
