# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20161024_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact person'),
        ),
    ]
