# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_location_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='send_thank_you_email',
            field=models.BooleanField(default=False, verbose_name="Send 'Thank You' email"),
        ),
        migrations.AddField(
            model_name='district',
            name='thank_you_email_template',
            field=models.TextField(blank=True, verbose_name="'Thank You' email message"),
        ),
    ]
