# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignLocationShiftVolunteers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='campaignlocationshift',
            name='volunteers',
        ),
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(default='kirjeldus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaignlocationshiftvolunteers',
            name='campaign_location_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.CampaignLocationShift'),
        ),
        migrations.AddField(
            model_name='campaignlocationshiftvolunteers',
            name='volunteers',
            field=models.ManyToManyField(to='volunteers.Volunteer'),
        ),
    ]
