# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-28 13:08
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_auto_20160820_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='description',
        ),
        migrations.AddField(
            model_name='campaign',
            name='registration_form_footer',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='registration_form_header',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='registration_form_right_panel',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
