# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-28 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_auto_20160828_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='campaignlocationshift',
            options={'verbose_name': 'Campaign shift', 'verbose_name_plural': 'Campaign shifts'},
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end',
            field=models.DateField(verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='registration_form_footer',
            field=tinymce.models.HTMLField(verbose_name='Registration form footer'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='registration_form_header',
            field=tinymce.models.HTMLField(verbose_name='Registration form header'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='registration_form_right_panel',
            field=tinymce.models.HTMLField(verbose_name='Registration form right panel'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start',
            field=models.DateField(verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='campaignlocationshift',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaign', verbose_name='Campaign'),
        ),
        migrations.AlterField(
            model_name='campaignlocationshift',
            name='day',
            field=models.DateField(verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='campaignlocationshift',
            name='end',
            field=models.TimeField(verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='campaignlocationshift',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='campaignlocationshift',
            name='start',
            field=models.TimeField(verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='campaignlocationshift',
            name='total_places',
            field=models.IntegerField(verbose_name='Total places'),
        ),
        migrations.AlterField(
            model_name='campaignlocationshift',
            name='volunteers',
            field=models.ManyToManyField(blank=True, to='volunteers.Volunteer', verbose_name='Volunteers'),
        ),
    ]
