# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-29 15:41
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_auto_20160828_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignlocationshift',
            options={'ordering': ['location__district__name', 'location__name', 'day', 'start'], 'verbose_name': 'Campaign shift', 'verbose_name_plural': 'Campaign shifts'},
        ),
        migrations.AddField(
            model_name='campaign',
            name='registration_confirmation_template',
            field=tinymce.models.HTMLField(default='', verbose_name='Registration confirmation template'),
            preserve_default=False,
        ),
    ]
