# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_campaignlocationshift_shift_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='summary',
            field=models.CharField(default='', max_length=200, verbose_name='Summary'),
            preserve_default=False,
        ),
    ]
