# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_campaign_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignlocationshift',
            name='shift_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_leader', to='volunteers.Volunteer', verbose_name='Shift leader'),
        ),
    ]
