# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0018_volunteer_public_notes'),
        ('campaigns', '0013_auto_20161127_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignLocationShiftParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_notes', models.TextField(blank=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.CampaignLocationShift')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Volunteer')),
            ],
        ),
    ]
