# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 14:14
from __future__ import unicode_literals

from django.db import migrations

def populate_campaignlocationshiftparticipations(apps, schema_editor):
    CampaignLocationShiftParticipation = apps.get_model('campaigns', 'CampaignLocationShiftParticipation')
    CampaignLocationShift = apps.get_model('campaigns', 'CampaignLocationShift')
    for shift in CampaignLocationShift.objects.all():
        for volunteer in shift.volunteers.all():
            CampaignLocationShiftParticipation.objects.create(shift=shift,
                    volunteer=volunteer)

class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_campaignlocationshiftparticipation'),
    ]

    operations = [
        migrations.RunPython(populate_campaignlocationshiftparticipations)
    ]
