# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_auto_20161204_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignlocationshift',
            name='volunteers',
        ),
    ]
