# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0018_volunteer_public_notes'),
        ('campaigns', '0016_remove_campaignlocationshift_volunteers'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlocationshift',
            name='volunteers',
            field=models.ManyToManyField(blank=True, through='campaigns.CampaignLocationShiftParticipation', to='volunteers.Volunteer', verbose_name='Volunteers'),
        ),
    ]
