# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_campaignlocationshift_volunteers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignlocationshiftparticipation',
            name='public_notes',
        ),
        migrations.AddField(
            model_name='campaignlocationshiftparticipation',
            name='shift_public_notes',
            field=models.TextField(blank=True, verbose_name='Shift public notes'),
        ),
        migrations.AlterField(
            model_name='campaignlocationshiftparticipation',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.CampaignLocationShift', verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='campaignlocationshiftparticipation',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Volunteer', verbose_name='Volunteer'),
        ),
    ]
