# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0018_volunteer_public_notes'),
        ('campaigns', '0019_campaignlocationshiftparticipation_was_present'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaignlocationshiftparticipation',
            unique_together=set([('volunteer', 'shift')]),
        ),
    ]
