# Generated by Django 2.0.5 on 2018-11-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_auto_20161206_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignlocationshiftparticipation',
            name='was_present',
        ),
        migrations.AddField(
            model_name='campaignlocationshiftparticipation',
            name='was_not_present',
            field=models.BooleanField(default=False, verbose_name='Was not present'),
        ),
    ]
